spring:
  application:
    name: usuario
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/${DB_NAME:usuario}?useTimezone=true&serverTimezone=UTC-3&allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  rabbitmq:
    host: rabbitmq
    port: 5672

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

usuario:
  rabbitmq:
    exchange: usuario.events.exchange